FROM alpine:3.20

RUN apk add --no-cache \
    bash \
    curl \
    iproute2 \
    iptables \
    nftables \
    wireguard-tools \
    python3 \
    iputils \
    netcat-openbsd

CMD ["sleep", "infinity"]
