/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddPeerDialog: typeof import('./components/canvas/overlays/AddPeerDialog.vue')['default']
    AddServiceDialog: typeof import('./components/canvas/overlays/AddServiceDialog.vue')['default']
    AddSubnetDialog: typeof import('./components/canvas/overlays/AddSubnetDialog.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BrandLogo: typeof import('./components/BrandLogo.vue')['default']
    CanvasStage: typeof import('./components/canvas/CanvasStage.vue')['default']
    ConfirmCutLinkDialog: typeof import('./components/canvas/overlays/ConfirmCutLinkDialog.vue')['default']
    ConfirmDeletePeerDialog: typeof import('./components/canvas/overlays/ConfirmDeletePeerDialog.vue')['default']
    ConfirmDeleteSubnetDialog: typeof import('./components/canvas/overlays/ConfirmDeleteSubnetDialog.vue')['default']
    CutLinkDialog: typeof import('./components/canvas/overlays/CutLinkDialog.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LinkTypeDialog: typeof import('./components/canvas/overlays/LinkTypeDialog.vue')['default']
    NetworkCanvas: typeof import('./components/NetworkCanvas.vue')['default']
    NetworkContext: typeof import('./components/canvas/overlays/NetworkContext.vue')['default']
    NetworkInspector: typeof import('./components/NetworkInspector.vue')['default']
    NetworkMenu: typeof import('./components/canvas/overlays/NetworkMenu.vue')['default']
    PeerConfigDialog: typeof import('./components/canvas/overlays/PeerConfigDialog.vue')['default']
    PeerContext: typeof import('./components/canvas/overlays/PeerContext.vue')['default']
    PeerDetailsDialog: typeof import('./components/canvas/overlays/PeerDetailsDialog.vue')['default']
    PeerMenu: typeof import('./components/canvas/overlays/PeerMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubnetContext: typeof import('./components/canvas/overlays/SubnetContext.vue')['default']
    SubnetInfoDialog: typeof import('./components/canvas/overlays/SubnetInfoDialog.vue')['default']
    SubnetMenu: typeof import('./components/canvas/overlays/SubnetMenu.vue')['default']
  }
}
